production:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: caminio
  options:
    include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    use_activesupport_time_zone: false
    use_utc: true
development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: caminio-dev
  options:
    include_root_in_json: true
    include_type_for_serialization: true
    preload_models: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    use_activesupport_time_zone: false
    use_utc: true
test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: caminio-test
  options:
    include_root_in_json: true
    include_type_for_serialization: true
    scope_overwrite_exception: true
    raise_not_found_error: false
    use_activesupport_time_zone: false
    use_utc: true